import { StyleSheet, Dimensions } from 'react-native';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f7fa',
    position: 'relative',
  },
  dateSelector: {
    backgroundColor: '#ffffff',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  dateSelectorContent: {
    paddingHorizontal: 15,
  },
  dayItem: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 50,
    height: 70,
    marginHorizontal: 5,
    borderRadius: 10,
    backgroundColor: '#f5f5f5',
  },
  selectedDayItem: {
    backgroundColor: '#3498DB',
  },
  dayText: {
    fontSize: 14,
    color: '#7F8C8D',
    marginBottom: 5,
  },
  dateText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2C3E50',
  },
  selectedText: {
    color: '#FFFFFF',
  },
  loaderContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 40,
  },
  loadingText: {
    marginTop: 15,
    fontSize: 16,
    color: '#7F8C8D',
  },  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 40,
    paddingHorizontal: 20,
  },
  errorTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#2C3E50',
    marginTop: 15,
    marginBottom: 5,
  },
  errorText: {
    fontSize: 16,
    color: '#7F8C8D',
    textAlign: 'center',
    marginBottom: 20,
    paddingHorizontal: 10,
    lineHeight: 22,
  },
  errorButtonsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    paddingHorizontal: 20,
    marginTop: 15,
  },
  retryButton: {
    backgroundColor: '#3498DB',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 140,
  },
  retryButtonText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 16,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  searchBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
    borderRadius: 10,
    paddingHorizontal: 15,
    paddingVertical: 10,
    marginRight: 10,
  },
  searchPlaceholder: {
    color: '#7F8C8D',
    fontSize: 16,
    marginLeft: 10,
  },
  addButton: {
    backgroundColor: '#3498DB',
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },  medicationsContainer: {
    flex: 1,
    paddingTop: 15,
    paddingHorizontal: 15,
  },
  medicationsScrollContainer: {
    flex: 1,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#2C3E50',
    marginBottom: 15,
  },
  medicationsList: {
    paddingBottom: 10,
  },  medicationCard: {
    width: '100%',
    height: 130, // Reduced height for better information display
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    marginBottom: 15,
    padding: 0,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    overflow: 'hidden',
    position: 'relative',
  },
  cardScrollContainer: {
    flexGrow: 1,
  },
  cardScrollPage: {
    width: SCREEN_WIDTH - 30,
  },  cardPage: {
    flex: 1,
    padding: 20,
    backgroundColor: 'transparent',
  },  medicationCardContent: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 18,
    paddingBottom: 12,
  },
  medicationInfo: {
    flex: 1,
    justifyContent: 'flex-start',
  },
  medicationName: {
    fontSize: 19,
    fontWeight: '700',
    color: '#2C3E50',
    marginBottom: 5,
    letterSpacing: -0.2,
  },
  medicationTimeAndDosage: {
    fontSize: 14,
    color: '#7F8C8D',
    fontWeight: '600',
  },cardPageTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#2C3E50',
    marginBottom: 18,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(230, 230, 230, 0.8)',
    paddingBottom: 10,
  },cardDetailsContainer: {
    flex: 1,
    paddingHorizontal: 5,
  },
  cardDetailRow: {
    flexDirection: 'row',
    marginBottom: 18,
  },
  cardDetailItem: {
    flex: 1,
    marginRight: 12,
  },
  cardDetailFull: {
    flex: 1,
  },
  cardDetailLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#7F8C8D',
    marginBottom: 6,
    letterSpacing: 0.3,
  },
  cardDetailValue: {
    fontSize: 15,
    color: '#2C3E50',
    fontWeight: '600',
  },  paginationDotsContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    bottom: 10,
    left: 0,
    right: 0,
  },
  paginationDot: {
    width: 3,
    height: 3,
    borderRadius: 1.5,
    backgroundColor: 'rgba(0,0,0,0.15)',
    marginHorizontal: 2,
  },
  activePaginationDot: {
    backgroundColor: '#3498DB',
    width: 10,
    height: 3,
    borderRadius: 1.5,
  },editButton: {
    position: 'absolute',
    top: 10,
    right: 10,
    backgroundColor: '#3498DB',
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 3,
  },  pillImageContainer: {
    width: 45,
    height: 45,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 5,
  },
  pillHalf: {
    width: 34,
    height: 14,
    borderRadius: 7,
    position: 'absolute',
  },
  pillCapsule: {
    width: 34,
    height: 14,
    borderRadius: 7,
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
  },
  pillRound: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#FFFFFF',
    borderWidth: 0.5,
    borderColor: 'rgba(0, 0, 0, 0.1)',
  },
  pillSpeckles: {
    width: 15,
    height: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    borderRadius: 2,
  },  takenContainer: {
    marginTop: 5,eft: {  },
  takenIconCircle: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#E6E9FF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  swipeIndicatorLeft: {
    position: 'absolute',
    left: 10,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 0.7,
    zIndex: 1,
  },
  swipeIndicatorRight: {
    position: 'absolute',
    right: 10,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 0.7,
    zIndex: 1,
  },
  swipeIndicatorText: {
    fontSize: 10,
    marginTop: 5,
    color: '#707070',
    fontWeight: '500',
  },
  skippedContainer: {
    marginTop: 5,
  },
  skippedIconCircle: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#FFEBEE',
    justifyContent: 'center',
    alignItems: 'center',
  },
  medicationFooter: {
    position: 'absolute',
    bottom: 10,
    right: 16,
    alignItems: 'flex-end',
  },
  lastTakenText: {
    fontSize: 9,
    color: '#95A5A6',
    marginBottom: 3,
    fontWeight: '500',
  },
  progressDotsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  progressDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    marginRight: 3,
  },
  activeDot: {
    backgroundColor: '#6B5DFF',
  },
  inactiveDot: {
    backgroundColor: '#E0E0E0',
  },
  emptyState: {
    height: 200,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 30,
    backgroundColor: '#F8F9FA',
    borderRadius: 20,  },
  emptyStateText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#95A5A6',
    marginTop: 15,
  },
  emptyStateSubtext: {
    fontSize: 14,
    color: '#95A5A6',
    marginTop: 5,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#FFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 20,
    paddingBottom: 30,
    height: '80%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginBottom: 15,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2C3E50',
  },
  searchInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
    borderRadius: 10,
    paddingHorizontal: 15,
    marginHorizontal: 20,
    marginBottom: 15,
    height: 45,
  },
  searchInput: {
    flex: 1,
    marginLeft: 10,
    fontSize: 16,
  },
  searchResultItem: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F5F5F5',
  },
  searchResultName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2C3E50',
  },
  searchResultDesc: {
    fontSize: 14,
    color: '#7F8C8D',
    marginTop: 3,
  },
  noResultsContainer: {
    alignItems: 'center',
    padding: 20,
  },
  noResultsText: {
    fontSize: 16,
    color: '#95A5A6',
  },
  formModalContent: {
    backgroundColor: '#FFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 20,
    paddingBottom: 30,
    height: '90%',
  },
  formScrollView: {
    flex: 1,
    paddingHorizontal: 20,
  },
  formField: {
    marginBottom: 20,
  },
  formLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#2C3E50',
    marginBottom: 8,  },
  formInput: {
    backgroundColor: '#F5F5F5',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
  },
  textArea: {
    height: 80,
    textAlignVertical: 'top',
  },
  timePickerContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  timePickerOption: {
    backgroundColor: '#F5F5F5',
    borderRadius: 30,
    paddingHorizontal: 15,
    paddingVertical: 8,
    marginRight: 10,
    marginBottom: 10,
  },
  timePickerSelected: {
    backgroundColor: '#3498DB',
  },
  timePickerText: {
    fontSize: 14,
    color: '#7F8C8D',
  },
  timePickerTextSelected: {
    color: '#FFF',
  },
  formActions: {
    paddingHorizontal: 20,
    paddingTop: 10,
  },
  saveButton: {
    backgroundColor: '#3498DB',
    borderRadius: 8,
  },
  saveButtonText: {
    fontSize: 16,
    fontWeight: '600',
  },
  formSectionHeader: {
    fontSize: 18,
    fontWeight: '600',
    color: '#2C3E50',
    marginTop: 10,
    marginBottom: 15,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#f0f0f0',
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  refreshButton: {
    padding: 5,
  },  mockDataBanner: {
    backgroundColor: '#FF9800',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    paddingHorizontal: 15,
    marginBottom: 15,
    borderRadius: 8,
    marginHorizontal: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  mockDataText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
    marginLeft: 8,
    flexShrink: 1,
  },
  // Add styles for pill type selection
  pillTypeContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  pillTypeOption: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
    borderRadius: 8,
    padding: 12,
    marginRight: 8,
    marginBottom: 12,
    width: '47%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  pillTypeSelected: {
    backgroundColor: '#E6E9FF',
    borderColor: '#3498DB',
    borderWidth: 2,
    shadowColor: '#3498DB',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  pillTypeText: {
    fontSize: 14,
    color: '#2C3E50',
    marginLeft: 6,
    fontWeight: '500',
  },
  pillTypeTextSelected: {
    color: '#3498DB',
    fontWeight: '700',
  },
  swipeIndicatorLeft: {
    position: 'absolute',
    left: 10,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 0.7,
    zIndex: 1,
  },
  swipeIndicatorRight: {
    position: 'absolute',
    right: 10,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 0.7,
    zIndex: 1,
  },
  swipeIndicatorText: {
    fontSize: 10,
    marginTop: 5,
    color: '#707070',
    fontWeight: '500',
  },
  takenContainer: {
    marginTop: 5,
  },
  takenIconCircle: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#E6E9FF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  skippedContainer: {
    marginTop: 5,
  },
  skippedIconCircle: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#FFEBEE',
    justifyContent: 'center',
    alignItems: 'center',
  },
  medicationFooter: {
    position: 'absolute',
    bottom: 10,
    right: 16,
    alignItems: 'flex-end',
  },
  lastTakenText: {
    fontSize: 9,
    color: '#95A5A6',
    marginBottom: 3,
    fontWeight: '500',
  },
  progressDotsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  progressDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    marginRight: 3,
  },
  activeDot: {
    backgroundColor: '#6B5DFF',
  },
  inactiveDot: {
    backgroundColor: '#E0E0E0',
  },emptyState: {
    height: 200,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 30,
    backgroundColor: '#F8F9FA',
    borderRadius: 20,
  },
  emptyStateText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#95A5A6',
    marginTop: 15,
  },
  emptyStateSubtext: {
    fontSize: 14,
    color: '#95A5A6',
    marginTop: 5,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#FFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 20,
    paddingBottom: 30,
    height: '80%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginBottom: 15,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2C3E50',
  },
  searchInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
    borderRadius: 10,
    paddingHorizontal: 15,
    marginHorizontal: 20,
    marginBottom: 15,
    height: 45,
  },
  searchInput: {
    flex: 1,
    marginLeft: 10,
    fontSize: 16,
  },
  searchResultItem: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F5F5F5',
  },
  searchResultName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2C3E50',
  },
  searchResultDesc: {
    fontSize: 14,
    color: '#7F8C8D',
    marginTop: 3,
  },
  noResultsContainer: {
    alignItems: 'center',
    padding: 20,
  },
  noResultsText: {
    fontSize: 16,
    color: '#95A5A6',
  },
  formModalContent: {
    backgroundColor: '#FFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 20,
    paddingBottom: 30,
    height: '90%',
  },
  formScrollView: {
    flex: 1,
    paddingHorizontal: 20,
  },
  formField: {
    marginBottom: 20,
  },
  formLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#2C3E50',
    marginBottom: 8,
  },
  formInput: {
    backgroundColor: '#F5F5F5',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
  },
  textArea: {
    height: 80,
    textAlignVertical: 'top',
  },
  timePickerContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  timePickerOption: {
    backgroundColor: '#F5F5F5',
    borderRadius: 30,
    paddingHorizontal: 15,
    paddingVertical: 8,
    marginRight: 10,
    marginBottom: 10,
  },
  timePickerSelected: {
    backgroundColor: '#3498DB',
  },
  timePickerText: {
    fontSize: 14,
    color: '#7F8C8D',
  },
  timePickerTextSelected: {
    color: '#FFF',
  },
  formActions: {
    paddingHorizontal: 20,
    paddingTop: 10,
  },
  saveButton: {
    backgroundColor: '#3498DB',
    borderRadius: 8,
  },  saveButtonText: {
    fontSize: 16,
    fontWeight: '600',
  },
  formSectionHeader: {
    fontSize: 18,
    fontWeight: '600',
    color: '#2C3E50',
    marginTop: 10,
    marginBottom: 15,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#f0f0f0',
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  refreshButton: {
    padding: 5,
  },  mockDataBanner: {
    backgroundColor: '#FF9800',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    paddingHorizontal: 15,
    marginBottom: 15,
    borderRadius: 8,
    marginHorizontal: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  mockDataText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
    marginLeft: 8,
    flexShrink: 1,
  },
  // Add styles for pill type selection
  pillTypeContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  pillTypeOption: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
    borderRadius: 8,
    padding: 12,
    marginRight: 8,
    marginBottom: 12,
    width: '47%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  pillTypeSelected: {
    backgroundColor: '#E6E9FF',
    borderColor: '#3498DB',
    borderWidth: 2,
    shadowColor: '#3498DB',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  pillTypeText: {
    fontSize: 14,
    color: '#2C3E50',
    marginLeft: 6,
    fontWeight: '500',
  },
  pillTypeTextSelected: {
    color: '#3498DB',
    fontWeight: '700',
  },
  swipeIndicatorLeft: {
    position: 'absolute',
    left: 10,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 0.7,
    zIndex: 1,
  },
  swipeIndicatorRight: {
    position: 'absolute',
    right: 10,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 0.7,
    zIndex: 1,
  },
  swipeIndicatorText: {
    fontSize: 10,
    marginTop: 5,
    color: '#707070',
    fontWeight: '500',
  },
  takenContainer: {
    marginTop: 5,
  },
  takenIconCircle: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#E6E9FF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  skippedContainer: {
    marginTop: 5,
  },
  skippedIconCircle: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#FFEBEE',
    justifyContent: 'center',
    alignItems: 'center',
  },
  medicationFooter: {
    position: 'absolute',
    bottom: 10,
    right: 16,
    alignItems: 'flex-end',
  },
  lastTakenText: {
    fontSize: 9,
    color: '#95A5A6',
    marginBottom: 3,
    fontWeight: '500',
  },
  progressDotsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  progressDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    marginRight: 3,
  },
  activeDot: {
    backgroundColor: '#6B5DFF',
  },
  inactiveDot: {
    backgroundColor: '#E0E0E0',
  },emptyState: {
    height: 200,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 30,
    backgroundColor: '#F8F9FA',
    borderRadius: 20,
  },
  emptyStateText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#95A5A6',
    marginTop: 15,
  },
  emptyStateSubtext: {
    fontSize: 14,
    color: '#95A5A6',
    marginTop: 5,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#FFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 20,
    paddingBottom: 30,
    height: '80%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginBottom: 15,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2C3E50',
  },
  searchInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
    borderRadius: 10,
    paddingHorizontal: 15,
    marginHorizontal: 20,
    marginBottom: 15,
    height: 45,
  },
  searchInput: {
    flex: 1,
    marginLeft: 10,
    fontSize: 16,
  },
  searchResultItem: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F5F5F5',
  },
  searchResultName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2C3E50',
  },
  searchResultDesc: {
    fontSize: 14,
    color: '#7F8C8D',
    marginTop: 3,
  },
  noResultsContainer: {
    alignItems: 'center',
    padding: 20,
  },
  noResultsText: {
    fontSize: 16,
    color: '#95A5A6',
  },
  formModalContent: {
    backgroundColor: '#FFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 20,
    paddingBottom: 30,
    height: '90%',
  },
  formScrollView: {
    flex: 1,
    paddingHorizontal: 20,
  },
  formField: {
    marginBottom: 20,
  },
  formLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#2C3E50',
    marginBottom: 8,
  },
  formInput: {
    backgroundColor: '#F5F5F5',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
  },
  textArea: {
    height: 80,
    textAlignVertical: 'top',
  },
  timePickerContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  timePickerOption: {
    backgroundColor: '#F5F5F5',
    borderRadius: 30,
    paddingHorizontal: 15,
    paddingVertical: 8,
    marginRight: 10,
    marginBottom: 10,
  },
  timePickerSelected: {
    backgroundColor: '#3498DB',
  },
  timePickerText: {
    fontSize: 14,
    color: '#7F8C8D',
  },
  timePickerTextSelected: {
    color: '#FFF',
  },
  formActions: {
    paddingHorizontal: 20,
    paddingTop: 10,
  },
  saveButton: {
    backgroundColor: '#3498DB',
    borderRadius: 8,
  },  saveButtonText: {
    fontSize: 16,
    fontWeight: '600',
  },
  formSectionHeader: {
    fontSize: 18,
    fontWeight: '600',
    color: '#2C3E50',
    marginTop: 10,
    marginBottom: 15,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#f0f0f0',
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  refreshButton: {
    padding: 5,
  },  mockDataBanner: {
    backgroundColor: '#FF9800',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    paddingHorizontal: 15,
    marginBottom: 15,
    borderRadius: 8,
    marginHorizontal: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  mockDataText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
    marginLeft: 8,
    flexShrink: 1,
  },
  // Add styles for pill type selection
  pillTypeContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  pillTypeOption: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
    borderRadius: 8,
    padding: 12,
    marginRight: 8,
    marginBottom: 12,
    width: '47%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  pillTypeSelected: {
    backgroundColor: '#E6E9FF',
    borderColor: '#3498DB',
    borderWidth: 2,
    shadowColor: '#3498DB',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  pillTypeText: {
    fontSize: 14,
    color: '#2C3E50',
    marginLeft: 6,
    fontWeight: '500',
  },
  pillTypeTextSelected: {
    color: '#3498DB',
    fontWeight: '700',
  },
  swipeIndicatorLeft: {
    position: 'absolute',
    left: 10,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 0.7,
    zIndex: 1,
  },
  swipeIndicatorRight: {
    position: 'absolute',
    right: 10,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 0.7,
    zIndex: 1,
  },
  swipeIndicatorText: {
    fontSize: 10,
    marginTop: 5,
    color: '#707070',
    fontWeight: '500',
  },
  takenContainer: {
    marginTop: 5,
  },
  takenIconCircle: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#E6E9FF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  skippedContainer: {
    marginTop: 5,
  },
  skippedIconCircle: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#FFEBEE',
    justifyContent: 'center',
    alignItems: 'center',
  },
  medicationFooter: {
    position: 'absolute',
    bottom: 10,
    right: 16,
    alignItems: 'flex-end',
  },
  lastTakenText: {
    fontSize: 9,
    color: '#95A5A6',
    marginBottom: 3,
    fontWeight: '500',
  },
  progressDotsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  progressDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    marginRight: 3,
  },
  activeDot: {
    backgroundColor: '#6B5DFF',
  },
  inactiveDot: {
    backgroundColor: '#E0E0E0',
  },emptyState: {
    height: 200,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 30,
    backgroundColor: '#F8F9FA',
    borderRadius: 20,
  },
  emptyStateText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#95A5A6',
    marginTop: 15,
  },
  emptyStateSubtext: {
    fontSize: 14,
    color: '#95A5A6',
    marginTop: 5,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#FFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 20,
    paddingBottom: 30,
    height: '80%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginBottom: 15,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2C3E50',
  },
  searchInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
    borderRadius: 10,
    paddingHorizontal: 15,
    marginHorizontal: 20,
    marginBottom: 15,
    height: 45,
  },
  searchInput: {
    flex: 1,
    marginLeft: 10,
    fontSize: 16,
  },
  searchResultItem: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F5F5F5',
  },
  searchResultName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2C3E50',
  },
  searchResultDesc: {
    fontSize: 14,
    color: '#7F8C8D',
    marginTop: 3,
  },
  noResultsContainer: {
    alignItems: 'center',
    padding: 20,
  },
  noResultsText: {
    fontSize: 16,
    color: '#95A5A6',
  },
  formModalContent: {
    backgroundColor: '#FFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 20,
    paddingBottom: 30,
    height: '90%',
  },
  formScrollView: {
    flex: 1,
    paddingHorizontal: 20,
  },
  formField: {
    marginBottom: 20,
  },
  formLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#2C3E50',
    marginBottom: 8,
  },
  formInput: {
    backgroundColor: '#F5F5F5',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
  },
  textArea: {
    height: 80,
    textAlignVertical: 'top',
  },
  timePickerContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  timePickerOption: {
    backgroundColor: '#F5F5F5',
    borderRadius: 30,
    paddingHorizontal: 15,
    paddingVertical: 8,
    marginRight: 10,
    marginBottom: 10,
  },
  timePickerSelected: {
    backgroundColor: '#3498DB',
  },
  timePickerText: {
    fontSize: 14,
    color: '#7F8C8D',
  },
  timePickerTextSelected: {
    color: '#FFF',
  },
  formActions: {
    paddingHorizontal: 20,
    paddingTop: 10,
  },
  saveButton: {
    backgroundColor: '#3498DB',
    borderRadius: 8,
  },  saveButtonText: {
    fontSize: 16,
    fontWeight: '600',
  },
  formSectionHeader: {
    fontSize: 18,
    fontWeight: '600',
    color: '#2C3E50',
    marginTop: 10,
    marginBottom: 15,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#f0f0f0',
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  refreshButton: {
    padding: 5,
  },  mockDataBanner: {
    backgroundColor: '#FF9800',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    paddingHorizontal: 15,
    marginBottom: 15,
    borderRadius: 8,
    marginHorizontal: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  mockDataText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
    marginLeft: 8,
    flexShrink: 1,
  },
  // Add styles for pill type selection
  pillTypeContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  pillTypeOption: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
    borderRadius: 8,
    padding: 12,
    marginRight: 8,
    marginBottom: 12,
    width: '47%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  pillTypeSelected: {
    backgroundColor: '#E6E9FF',
    borderColor: '#3498DB',
    borderWidth: 2,
    shadowColor: '#3498DB',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  pillTypeText: {
    fontSize: 14,
    color: '#2C3E50',
    marginLeft: 6,
    fontWeight: '500',
  },
  pillTypeTextSelected: {
    color: '#3498DB',
    fontWeight: '700',
  },
  swipeIndicatorLeft: {
    position: 'absolute',
    left: 10,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 0.7,
    zIndex: 1,
  },
  swipeIndicatorRight: {
    position: 'absolute',
    right: 10,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 0.7,
    zIndex: 1,
  },
  swipeIndicatorText: {
    fontSize: 10,
    marginTop: 5,
    color: '#707070',
    fontWeight: '500',
  },
  takenContainer: {
    marginTop: 5,
  },
  takenIconCircle: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#E6E9FF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  skippedContainer: {
    marginTop: 5,
  },
  skippedIconCircle: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#FFEBEE',
    justifyContent: 'center',
    alignItems: 'center',
  },
  medicationFooter: {
    position: 'absolute',
    bottom: 10,
    right: 16,
    alignItems: 'flex-end',
  },
  lastTakenText: {
    fontSize: 9,
    color: '#95A5A6',
    marginBottom: 3,
    fontWeight: '500',
  },
  progressDotsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  progressDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    marginRight: 3,
  },
  activeDot: {
    backgroundColor: '#6B5DFF',
  },
  inactiveDot: {
    backgroundColor: '#E0E0E0',
  },emptyState: {
    height: 200,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 30,
    backgroundColor: '#F8F9FA',
    borderRadius: 20,
  },
  emptyStateText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#95A5A6',
    marginTop: 15,
  },
  emptyStateSubtext: {
    fontSize: 14,
    color: '#95A5A6',
    marginTop: 5,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#FFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 20,
    paddingBottom: 30,
    height: '80%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginBottom: 15,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2C3E50',
  },
  searchInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
    borderRadius: 10,
    paddingHorizontal: 15,
    marginHorizontal: 20,
    marginBottom: 15,
    height: 45,
  },
  searchInput: {
    flex: 1,
    marginLeft: 10,
    fontSize: 16,
  },
  searchResultItem: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F5F5F5',
  },
  searchResultName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2C3E50',
  },
  searchResultDesc: {
    fontSize: 14,
    color: '#7F8C8D',
    marginTop: 3,
  },
  noResultsContainer: {
    alignItems: 'center',
    padding: 20,
  },
  noResultsText: {
    fontSize: 16,
    color: '#95A5A6',
  },
  formModalContent: {
    backgroundColor: '#FFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 20,
    paddingBottom: 30,
    height: '90%',
  },
  formScrollView: {
    flex: 1,
    paddingHorizontal: 20,
  },
  formField: {
    marginBottom: 20,
  },
  formLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#2C3E50',
    marginBottom: 8,
  },
  formInput: {
    backgroundColor: '#F5F5F5',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
  },
  textArea: {
    height: 80,
    textAlignVertical: 'top',
  },
  timePickerContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  timePickerOption: {
    backgroundColor: '#F5F5F5',
    borderRadius: 30,
    paddingHorizontal: 15,
    paddingVertical: 8,
    marginRight: 10,
    marginBottom: 10,
  },
  timePickerSelected: {
    backgroundColor: '#3498DB',
  },
  timePickerText: {
    fontSize: 14,
    color: '#7F8C8D',
  },
  timePickerTextSelected: {
    color: '#FFF',
  },
  formActions: {
    paddingHorizontal: 20,
    paddingTop: 10,
  },
  saveButton: {
    backgroundColor: '#3498DB',
    borderRadius: 8,
  },  saveButtonText: {
    fontSize: 16,
    fontWeight: '600',
  },
  formSectionHeader: {
    fontSize: 18,
    fontWeight: '600',
    color: '#2C3E50',
    marginTop: 10,
    marginBottom: 15,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#f0f0f0',
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  refreshButton: {
    padding: 5,
  },  mockDataBanner: {
    backgroundColor: '#FF9800',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    paddingHorizontal: 15,
    marginBottom: 15,
    borderRadius: 8,
    marginHorizontal: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  mockDataText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
    marginLeft: 8,
    flexShrink: 1,
  },
  // Add styles for pill type selection
  pillTypeContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  pillTypeOption: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
    borderRadius: 8,
    padding: 12,
    marginRight: 8,
    marginBottom: 12,
    width: '47%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  pillTypeSelected: {
    backgroundColor: '#E6E9FF',
    borderColor: '#3498DB',
    borderWidth: 2,
    shadowColor: '#3498DB',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  pillTypeText: {
    fontSize: 14,
    color: '#2C3E50',
    marginLeft: 6,
    fontWeight: '500',
  },
  pillTypeTextSelected: {
    color: '#3498DB',
    fontWeight: '700',
  },
  swipeIndicatorLeft: {
    position: 'absolute',
    left: 10,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 0.7,
    zIndex: 1,
  },
  swipeIndicatorRight: {
    position: 'absolute',
    right: 10,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 0.7,
    zIndex: 1,
  },
  swipeIndicatorText: {
    fontSize: 10,
    marginTop: 5,
    color: '#707070',
    fontWeight: '500',
  },
  takenContainer: {
    marginTop: 5,
  },
  takenIconCircle: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#E6E9FF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  skippedContainer: {
    marginTop: 5,
  },
  skippedIconCircle: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#FFEBEE',
    justifyContent: 'center',
    alignItems: 'center',
  },
  medicationFooter: {
    position: 'absolute',
    bottom: 10,
    right: 16,
    alignItems: 'flex-end',
  },
  lastTakenText: {
    fontSize: 9,
    color: '#95A5A6',
    marginBottom: 3,
    fontWeight: '500',
  },
  progressDotsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  progressDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    marginRight: 3,
  },
  activeDot: {
    backgroundColor: '#6B5DFF',
  },
  inactiveDot: {
    backgroundColor: '#E0E0E0',
  },emptyState: {
    height: 200,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 30,
    backgroundColor: '#F8F9FA',
    borderRadius: 20,
  },
  emptyStateText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#95A5A6',
    marginTop: 15,
  },
  emptyStateSubtext: {
    fontSize: 14,
    color: '#95A5A6',
    marginTop: 5,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#FFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 20,
    paddingBottom: 30,
    height: '80%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginBottom: 15,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2C3E50',
  },
  searchInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
    borderRadius: 10,
    paddingHorizontal: 15,
    marginHorizontal: 20,
    marginBottom: 15,
    height: 45,
  },
  searchInput: {
    flex: 1,
    marginLeft: 10,
    fontSize: 16,
  },
  searchResultItem: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F5F5F5',
  },
  searchResultName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2C3E50',
  },
  searchResultDesc: {
    fontSize: 14,
    color: '#7F8C8D',
    marginTop: 3,
  },
  noResultsContainer: {
    alignItems: 'center',
    padding: 20,
  },
  noResultsText: {
    fontSize: 16,
    color: '#95A5A6',
  },
  formModalContent: {
    backgroundColor: '#FFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 20,
    paddingBottom: 30,
    height: '90%',
  },
  formScrollView: {
    flex: 1,
    paddingHorizontal: 20,
  },
  formField: {
    marginBottom: 20,
  },
  formLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#2C3E50',
    marginBottom: 8,
  },
  formInput: {
    backgroundColor: '#F5F5F5',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
  },
  textArea: {
    height: 80,
    textAlignVertical: 'top',
  },
  timePickerContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  timePickerOption: {
    backgroundColor: '#F5F5F5',
    borderRadius: 30,
    paddingHorizontal: 15,
    paddingVertical: 8,
    marginRight: 10,
    marginBottom: 10,
  },
  timePickerSelected: {
    backgroundColor: '#3498DB',
  },
  timePickerText: {
    fontSize: 14,
    color: '#7F8C8D',
  },
  timePickerTextSelected: {
    color: '#FFF',
  },
  formActions: {
    paddingHorizontal: 20,
    paddingTop: 10,
  },
  saveButton: {
    backgroundColor: '#3498DB',
    borderRadius: 8,
  },  saveButtonText: {
    fontSize: 16,
    fontWeight: '600',
  },
  formSectionHeader: {
    fontSize: 18,
    fontWeight: '600',
    color: '#2C3E50',
    marginTop: 10,
    marginBottom: 15,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#f0f0f0',
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  refreshButton: {
    padding: 5,
  },  mockDataBanner: {
    backgroundColor: '#FF9800',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    paddingHorizontal: 15,
    marginBottom: 15,
    borderRadius: 8,
    marginHorizontal: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  mockDataText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
    marginLeft: 8,
    flexShrink: 1,
  },
  // Add styles for pill type selection
  pillTypeContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  pillTypeOption: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
    borderRadius: 8,
    padding: 12,
    marginRight: 8,
    marginBottom: 12,
    width: '47%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  pillTypeSelected: {
    backgroundColor: '#E6E9FF',
    borderColor: '#3498DB',
    borderWidth: 2,
    shadowColor: '#3498DB',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  pillTypeText: {
    fontSize: 14,
    color: '#2C3E50',
    marginLeft: 6,
    fontWeight: '500',
  },
  pillTypeTextSelected: {
    color: '#3498DB',
    fontWeight: '700',
  },
  swipeIndicatorLeft: {
    position: 'absolute',
    left: 10,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 0.7,
    zIndex: 1,
  },
  swipeIndicatorRight: {
    position: 'absolute',
    right: 10,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 0.7,
    zIndex: 1,
  },
  swipeIndicatorText: {
    fontSize: 10,
    marginTop: 5,
    color: '#707070',
    fontWeight: '500',
  },
  takenContainer: {
    marginTop: 5,
  },
  takenIconCircle: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#E6E9FF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  skippedContainer: {
    marginTop: 5,
  },
  skippedIconCircle: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#FFEBEE',
    justifyContent: 'center',
    alignItems: 'center',
  },
  medicationFooter: {
    position: 'absolute',
    bottom: 10,
    right: 16,
    alignItems: 'flex-end',
  },
  lastTakenText: {
    fontSize: 9,
    color: '#95A5A6',
    marginBottom: 3,
    fontWeight: '500',
  },
  progressDotsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  progressDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    marginRight: 3,
  },
  activeDot: {
    backgroundColor: '#6B5DFF',
  },
  inactiveDot: {
    backgroundColor: '#E0E0E0',
  },emptyState: {
    height: 200,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 30,
    backgroundColor: '#F8F9FA',
    borderRadius: 20,
  },
  emptyStateText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#95A5A6',
    marginTop: 15,
  },
  emptyStateSubtext: {
    fontSize: 14,
    color: '#95A5A6',
    marginTop: 5,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#FFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 20,
    paddingBottom: 30,
    height: '80%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginBottom: 15,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2C3E50',
  },
  searchInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
    borderRadius: 10,
    paddingHorizontal: 15,
    marginHorizontal: 20,
    marginBottom: 15,
    height: 45,
  },
  searchInput: {
    flex: 1,
    marginLeft: 10,
    fontSize: 16,
  },
  searchResultItem: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F5F5F5',
  },
  searchResultName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2C3E50',
  },
  searchResultDesc: {
    fontSize: 14,
    color: '#7F8C8D',
    marginTop: 3,
  },
  noResultsContainer: {
    alignItems: 'center',
    padding: 20,
  },
  noResultsText: {
    fontSize: 16,
    color: '#95A5A6',
  },
  formModalContent: {
    backgroundColor: '#FFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 20,
    paddingBottom: 30,
    height: '90%',
  },
  formScrollView: {
    flex: 1,
    paddingHorizontal: 20,
  },
  formField: {
    marginBottom: 20,
  },
  formLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#2C3E50',
    marginBottom: 8,
  },
  formInput: {
    backgroundColor: '#F5F5F5',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
  },
  textArea: {
    height: 80,
    textAlignVertical: 'top',
  },
  timePickerContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  timePickerOption: {
    backgroundColor: '#F5F5F5',
    borderRadius: 30,
    paddingHorizontal: 15,
    paddingVertical: 8,
    marginRight: 10,
    marginBottom: 10,
  },
  timePickerSelected: {
    backgroundColor: '#3498DB',
  },
  timePickerText: {
    fontSize: 14,
    color: '#7F8C8D',
  },
  timePickerTextSelected: {
    color: '#FFF',
  },
  formActions: {
    paddingHorizontal: 20,
    paddingTop: 10,
  },
  saveButton: {
    backgroundColor: '#3498DB',
    borderRadius: 8,
  },  saveButtonText: {
    fontSize: 16,
    fontWeight: '600',
  },
  formSectionHeader: {
    fontSize: 18,
    fontWeight: '600',
    color: '#2C3E50',
    marginTop: 10,
    marginBottom: 15,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#f0f0f0',
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  refreshButton: {
    padding: 5,
  },  mockDataBanner: {
    backgroundColor: '#FF9800',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    paddingHorizontal: 15,
    marginBottom: 15,
    borderRadius: 8,
    marginHorizontal: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  mockDataText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
    marginLeft: 8,
    flexShrink: 1,
  },
  // Add styles for pill type selection
  pillTypeContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  pillTypeOption: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
    borderRadius: 8,
    padding: 12,
    marginRight: 8,
    marginBottom: 12,
    width: '47%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  pillTypeSelected: {
    backgroundColor: '#E6E9FF',
    borderColor: '#3498DB',
    borderWidth: 2,
    shadowColor: '#3498DB',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  pillTypeText: {
    fontSize: 14,
    color: '#2C3E50',
    marginLeft: 6,
    fontWeight: '500',
  },
  pillTypeTextSelected: {
    color: '#3498DB',
    fontWeight: '700',
  },
  swipeIndicatorLeft: {
    position: 'absolute',
    left: 10,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 0.7,
    zIndex: 1,
  },
  swipeIndicatorRight: {
    position: 'absolute',
    right: 10,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 0.7,
    zIndex: 1,
  },
  swipeIndicatorText: {
    fontSize: 10,
    marginTop: 5,
    color: '#707070',
    fontWeight: '500',
  },
  takenContainer: {
    marginTop: 5,
  },
  takenIconCircle: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#E6E9FF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  skippedContainer: {
    marginTop: 5,
  },
  skippedIconCircle: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#FFEBEE',
    justifyContent: 'center',
    alignItems: 'center',
  },
  medicationFooter: {
    position: 'absolute',
    bottom: 10,
    right: 16,
    alignItems: 'flex-end',
  },
  lastTakenText: {
    fontSize: 9,
    color: '#95A5A6',
    marginBottom: 3,
    fontWeight: '500',
  },
  progressDotsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  progressDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    marginRight: 3,
  },
  activeDot: {
    backgroundColor: '#6B5DFF',
  },
  inactiveDot: {
    backgroundColor: '#E0E0E0',
  },emptyState: {
    height: 200,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 30,
    backgroundColor: '#F8F9FA',
    borderRadius: 20,
  },
  emptyStateText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#95A5A6',
    marginTop: 15,
  },
  emptyStateSubtext: {
    fontSize: 14,
    color: '#95A5A6',
    marginTop: 5,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
    modalContent: {
        backgroundColor: '#FFF',
        borderTopLeftRadius: 50,
        borderTopRightRadius: 50,      }
  },
});

export { SCREEN_WIDTH };
export default styles;